apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  # These labels are deployemnt related labesl
  labels:
    component: mysql
    project: expense
    tier: database
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: database
  # pod defination
  template:
    metadata:
      # These labels are pod related lables
      labels:
         component: mysql
         project: expense
         tier: database
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
