apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  # These labels are deployemnt related labesl
  labels:
    component: mysql
    project: expense
    tier: database
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: database
  # pod defination
  template:
    metadata:
      # These labels are pod related lables
      labels:
         component: mysql
         project: expense
         tier: database
    spec:
      containers:
        - name: mysql
          image: aravind19981999/mysql-db:v1.0
          
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: database
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # target port on the pod